#Array basics

In [22]:
a=[10,20,30] #one dimensional

3-element Array{Int64,1}:
 10
 20
 30

In [23]:
a=["foo","bar",10]

3-element Array{Any,1}:
   "foo"
   "bar"
 10     

In [24]:
size(a)

(3,)

In [25]:
ndims(a)

1

In [26]:
eye(3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [27]:
diagm([2, 4])

2×2 Array{Int64,2}:
 2  0
 0  4

In [28]:
Array{Int64, 1} == Vector{Int64}

true

In [29]:
Array{Int64, 2} == Matrix{Int64}

true

In [30]:
Array{Int64, 1} == Matrix{Int64}

false

In [32]:
Array{Int64, 3} == Matrix{Int64}

false

In [34]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [36]:
b = reshape(a, 2, 2)

2×2 Array{Int64,2}:
 10  30
 20  40

In [37]:
a==b

false

In [38]:
b[1, 1] = 100

100

In [39]:
b

2×2 Array{Int64,2}:
 100  30
  20  40

In [40]:
a #element of a change as well

4-element Array{Int64,1}:
 100
  20
  30
  40

In [42]:
a = [1 2 3 4]  # Two dimensional

1×4 Array{Int64,2}:
 1  2  3  4

In [43]:
a

1×4 Array{Int64,2}:
 1  2  3  4

In [44]:
squeeze(a, 1)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [45]:
#create an empty array
x = Array{Float64}(2, 2)

2×2 Array{Float64,2}:
 7.33155e-316  6.10191e-316
 6.10194e-316  4.44992e-316

In [46]:
ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [47]:
fill("foo", 2, 2)

2×2 Array{String,2}:
 "foo"  "foo"
 "foo"  "foo"

In [48]:
ndims(a)

2

In [49]:
#two dimensional
a = [10 20 30 40]

1×4 Array{Int64,2}:
 10  20  30  40

In [50]:
a = [10 20; 30 40]  # 2 x 2

2×2 Array{Int64,2}:
 10  20
 30  40

In [51]:
a = [10; 20; 30; 40] #1 dimensitonal

4-element Array{Int64,1}:
 10
 20
 30
 40

In [52]:
a=[10,20,30,40] #1 dimensional

4-element Array{Int64,1}:
 10
 20
 30
 40

In [53]:
a = [10 20 30 40]'

4×1 Array{Int64,2}:
 10
 20
 30
 40

In [54]:
ndims(a)

2

## Array indexing

In [55]:
a=collect(10:10:40)

4-element Array{Int64,1}:
 10
 20
 30
 40

In [56]:
a[end-1]

30

In [57]:
a[1:3]

3-element Array{Int64,1}:
 10
 20
 30

In [58]:
a=rand(2,2)

2×2 Array{Float64,2}:
 0.177942  0.840201
 0.945168  0.42817 

In [59]:
a[1,1]

0.177941838225947

In [60]:
a[1,:] #first row

2-element Array{Float64,1}:
 0.177942
 0.840201

In [62]:
a[:,1] #first column

2-element Array{Float64,1}:
 0.177942
 0.945168

In [63]:
a = randn(2, 2)

2×2 Array{Float64,2}:
  1.44418  -1.805   
 -1.39509  -0.661992

In [64]:
b = [true false; false true]

2×2 Array{Bool,2}:
  true  false
 false   true

In [65]:
a[b]

2-element Array{Float64,1}:
  1.44418 
 -0.661992

In [66]:
a = Array{Float64}(4)

4-element Array{Float64,1}:
 4.49466e-316
 4.48339e-316
 4.43302e-316
 4.27567e-316

In [67]:
a[2:end]

3-element Array{Float64,1}:
 4.48339e-316
 4.43302e-316
 4.27567e-316

In [69]:
a[2:end]=42

42

In [70]:
a

4-element Array{Float64,1}:
  4.49466e-316
 42.0         
 42.0         
 42.0         

## Passing arrays

In [71]:
a = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [73]:
b=a

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [74]:
b[3] = 44

44

In [79]:
a

3-element Array{Float64,1}:
  1.0
  1.0
 44.0

In [80]:
a=ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [82]:
c=copy(a)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [83]:
c[3]=44

44

In [84]:
a

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

## operations on arrays

In [85]:
a=[-1,0,1]

3-element Array{Int64,1}:
 -1
  0
  1

In [86]:
length(a)

3

In [87]:
sum(a)

0

In [88]:
mean(a)

0.0

In [89]:
std(a)

1.0

In [91]:
maximum(a)

1

In [93]:
b=sort(a,rev=true) #new array

3-element Array{Int64,1}:
  1
  0
 -1

In [94]:
b==a

false

In [95]:
b = sort!(a, rev=true) # Returns *modified original* array

3-element Array{Int64,1}:
  1
  0
 -1

In [96]:
b==a

true

## Matrix algebra

In [100]:
a = ones(1, 2)

1×2 Array{Float64,2}:
 1.0  1.0

In [102]:
size(a)

(1, 2)

In [98]:
b = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [99]:
a*b

1×2 Array{Float64,2}:
 2.0  2.0

In [103]:
b * a'

2×1 Array{Float64,2}:
 2.0
 2.0

In [104]:
A = [1 2; 2 3]

2×2 Array{Int64,2}:
 1  2
 2  3

In [105]:
B = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [106]:
A \ B #more stable than inv(A) * B

2×2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

In [107]:
inv(A) * B

2×2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

In [108]:
ones(2) * ones(2) #can not multiply one-dim vector

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [109]:
dot(ones(2), ones(2))

2.0

In [110]:
b = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [113]:
b * ones(2)

2-element Array{Float64,1}:
 2.0
 2.0

In [112]:
ones(2) * b

LoadError: DimensionMismatch("A has dimensions (2,1) but B has dimensions (2,2)")

## Elementwise Operations

In [115]:
ones(2, 2) .* ones(2, 2)   # Element by element multiplication

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [116]:
A = -ones(2, 2)

2×2 Array{Float64,2}:
 -1.0  -1.0
 -1.0  -1.0

In [117]:
A.^2

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [118]:
ones(2, 2) + ones(2, 2) 

2×2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0

In [120]:
A = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [121]:
2 * A  # Same as 2 .* A

2×2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0

## Elementwise Comparisons

In [122]:
a = [10, 20, 30]

3-element Array{Int64,1}:
 10
 20
 30

In [123]:
b = [-100, 0, 100]

3-element Array{Int64,1}:
 -100
    0
  100

In [124]:
b .> a

3-element BitArray{1}:
 false
 false
  true

In [125]:
a .== b

3-element BitArray{1}:
 false
 false
 false

In [126]:
a==b

false

In [127]:
a=randn(4)

4-element Array{Float64,1}:
  2.13303 
 -0.531787
 -0.751304
 -0.982565

In [128]:
a.<0

4-element BitArray{1}:
 false
  true
  true
  true

In [129]:
a[a .< 0]

3-element Array{Float64,1}:
 -0.531787
 -0.751304
 -0.982565

## Vectorized Functions

In [130]:
log(1.0)

0.0

In [131]:
log.(ones(4)) #elementwise

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [132]:
[log(x) for x in ones(4)]

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [133]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [134]:
det(A)

-2.0

In [135]:
trace(A)

5

In [136]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [137]:
rank(A)

2

the excercise is about unconditional variance or asymptotic variance of the stochastic difference equation
see https://lectures.quantecon.org/jl/julia_arrays.html#operations-on-arrays